### ISSUE TITLE
Replace view mode's loading dialog with progress bar, add swipe action for next image

### ISSUE THREAD

**Issue by Null-Ouwenjie** [kurumi-moe/MoeGallery#1]
1、
加载大图时使用了ProgressDialog，遮住了原图，
并且后退键无法取消Dialog。
建议参考微博或微信的加载图片的方式）
2、
在大图模式下，必须退出页面重新点击才能查看另一张图片。
建议在里面加上可直接切换到上一张图和下一张图的交互。
~

**Comment by kurumi-moe** [comment]
Thanks for your report, I will add this feature in coming version.

**Comment by kurumi-moe** [comment]
1. Added non-blocking progress bar.
2. Added drag back gesture.
